### ISSUE TITLE
Cannot load the solution on Visual Studio for Mac

### ISSUE THREAD

**Issue by KevinHu-au** [reactivemarbles/SocialQ#1]
Hi @RLittlesII , got this reference repo from the ReactiveUI conf this morning. Thanks for the presentation. Very helpful and useful. 

After I cloned the repo, I cannot load the solution on VS 4 mac.

It was showing missing the the Sextant and Sextant.Plugins.Popup. I copy the Sextant source code to this solution src folder, and commented out Sextant.Plugins.Popup from .sln file, but still unable to load the solution.

Not sure anything else I need to do.

Thanks,
Kevin Hu

**Comment by RLittlesII** [comment]
I did a bad thing.  It's brought in as a git submodule.

From the root directory of the repo

`git submodule init`
`git submodule update`

Plan is to ship the feature and remove the submodule.

**Comment by KevinHu-au** [comment]
@RLittlesII Thank you and sorry for missing your reply.
